### ISSUE TITLE
Run time and memory requirements

### ISSUE THREAD

**Issue by paulyashna** [saezlab/liana#10]
Hi, 

Is it possible for you to comment on the run times of the tool at different number of cells? e.g. 5k? 10K etc. I have been trying with >10k cells and I think it would be a good option to downsample the seurat object. Has the consistency of results been checked at different downsampling thresholds?

Also, I would like to know run times and requirement of processing cores, if any when more than one method is being used at a time. If I run cellchat with 5k cells it is pretty fast. But as soon as I include another method the process never stops. How much time should this take approximately? A verbose=TRUE option would be nice to track the process. Greatly appreciate your thoughts on this.

Thanks,
Yashna

**Comment by deeenes** [comment]
> A verbose=TRUE option would be nice to track the process. 

@dbdimitrov  For this I can recommend `logger`: https://daroczig.github.io/logger/
We use it in OmnipathR: https://github.com/saezlab/OmnipathR/blob/e50affdeeab2f8b85b54b6d841d6a7a694eda7ab/R/options.R#L377

**Comment by dbdimitrov** [comment]
Hi Yashna,

I think I might have an idea what's behind this issue that you're observing.
I noticed that Connectome (when called via LIANA, but not via it's individual _pipe function) will hang until eternity for some data sets. Honestly, I could not find a reason why this happens, only pinpointed it to the `scaleData` function of Seurat when executed via `exec` or `do.call`. There seems to be [very little information](https://github.com/rstudio/rstudio/issues/5158) about this. 

For now, I would recommend excluding Connectome from the list of methods if this occurs for your dataset. I will reimplement the method soon and hopefully the issue will be resolved.

Regards,
Daniel

**Comment by paulyashna** [comment]
Thanks Daniel, for your comments and quick reply. This is certainly helpful. 
Best Regards,
Yashna

**Comment by dbdimitrov** [comment]
Hi paulyashna,

Just wanted to mention that the issue with Connectome should now be resolved.

Regards,
Daniel

**Comment by paulyashna** [comment]
Hi Daniel, Thanks for this, I shall check this out. Will you have an idea why I keep getting an error 'cell label should not contain 0' error with any of the methods I try. I understand the metadata information is directly taken from the seurat object. I have added cluster annotations under the column seurat_annotations in the metadata, and still get this error. I appreciate any help on this.
